### ISSUE TITLE
Start up Error?

### ISSUE THREAD

**Issue by QueenKisaki** [LapisPlugins/HomeSpawn_LEGACY#3]
I've been getting this error at start up: https://pastebin.com/nmXsQfzn

Version 2.2.2 on spigot 1.11.2

**Comment by Dart2112** [comment]
It's because one of the players has an unknown world in their config. so one of them set their home somewhere and then the world was removed or renamed and now it causes an error. see 19.07 09:53:58 [Server] ERROR Could not call method 'public static org.bukkit.Location org.bukkit.Location.deserialize(java.util.Map)' of class org.bukkit.Location for deserialization
19.07 09:53:58 [Server] INFO java.lang.IllegalArgumentException: unknown world. that's saying that it tried to load a location but it had an invalid world. I can quickly throw together a version that checks for this and will remove the home to stop it happening again. but for now see if you can find it manually if you don't have many player data files

**Comment by Dart2112** [comment]
sorry turn out the error is thrown when it attempts to load the config not when it loads the location. this means the only thing I can do to fix it is, manually go into each file and delete the homes for you or delete the player data entirely

**Comment by QueenKisaki** [comment]
I removed their player files completely and restarted, did not get the message. When they remake their homes in that world will it happen again?

**Comment by Dart2112** [comment]
As long as the world's they set their homes in are in worlds that exist they will be fine

**Comment by tomabrafix** [comment]
I have the same error message on startup. The problem is not a deleted world, the problem is that I'm using Multiverse and the homes are not on the first ('vanilla') world because the plugin tries to load the homes before the additional worlds are loaded on startup. Homes on the first world do not cause errors.

**Comment by Dart2112** [comment]
Making Homespawn soft depend multiverse should make it load after the world's have been loaded. I'll do some testing later

**Comment by Dart2112** [comment]
I've pushed the update to the GitHub auto updater, if one of you can test to see if it works with multiverse that would be great

**Comment by Dart2112** [comment]
use /homespawn update to install it or download it from GitHub manually

**Comment by tomabrafix** [comment]
It works for me. Thanks :)
